### ISSUE TITLE
Playwright 1.4.x

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#1015]
### Issues
- ~~ffmpeg needs to be installed (not available on circleci/node:12.18.2-buster-browsers)~~
  - ~~quick fix is to `sudo apt install ffmpeg`~~
  - ~~better fix would be to build custom docker image~~
- ~~domain.enter is not a function~~
- Must use playwright to launch firefox, which precludes using web-ext to load temporary add-on

### Status
~~Closed #1013 and will wait for another release which should hopefully fix these issues
It seems 1.4.1 should fix things~~
It seems now that that can not connect to a self launched FF
From [this comment](https://github.com/microsoft/playwright/issues/3932#issuecomment-696409074):
> Playwright now uses it's own protocol for communication between its client and server, so it is essential that the Playwright is used to launch the browser and obtain the web socket address.

Waiting on Playwright devs to come up with a solution

#### Playwright Github issues
- ~~https://github.com/microsoft/playwright/issues/3845~~
- ~~https://github.com/microsoft/playwright/issues/3848~~
- https://github.com/microsoft/playwright/issues/3932 (lastCheckedDate=8thOct)

### Notes

It seems the docker images require ffmpeg to be installed

Tried using the official playwright [docker image](https://hub.docker.com/_/microsoft-playwright) but make is missing, which we are using for sjcl (anonymous tokens):
```
Compression: none
/bin/sh: 1: make: not found
```

Installed ffmpeg via a `sudo apt install ffmpeg`

Now have an error with `domain.enter` is not a function:

```
+ yarn ts-node -r tsconfig-paths/register -T -P test/tsconfig.json test/playwright/logout-test.ts
yarn run v1.22.4
$ /home/circleci/project/node_modules/.bin/ts-node -r tsconfig-paths/register -T -P test/tsconfig.json test/playwright/logout-test.ts
TypeError: domain.enter is not a function
    at Proxy.EventEmitter.emit (domain.js:504:10)
    at Connection.dispatch (/home/circleci/project/node_modules/playwright/lib/client/connection.js:107:25)
    at Immediate.<anonymous> (/home/circleci/project/node_modules/playwright/lib/inprocess.js:39:85)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

This even happens locally on my Mac

Tried Node 14 to see if it was domain stdlib changes with #1016, but no dice

**Comment by sublimator** [comment]
https://github.com/microsoft/playwright/issues/3932

**Comment by sublimator** [comment]
https://github.com/microsoft/playwright/issues/3696#issuecomment-708203957
