### ISSUE TITLE
Extension privacy pass error when running web monetization demo with receipt verifier

### ISSUE THREAD

**Issue by sabinebertram** [coilhq/web-monetization-projects#695]
When trying to run the [web monetization demo using using Receipt Verifier](https://github.com/coilhq/web-monetization-projects/tree/master/packages/web-monetization-demo#running-the-demo-servers-and-client), STREAM did not start. I saw the following errors in the extension logs:
```
crypto.ts:254 [privacy-pass]: Recomputed digest does not equal received digest
verifyProof @ crypto.ts:254
crypto.ts:255 Computed digest: -6288427,1378301694,1565937502,-1264816874,-22875077,755117876,-744901949,-2143588477
verifyProof @ crypto.ts:255
crypto.ts:256 Received digest: -1537219438,590284884,1034896261,308249482,-1349293231,1397054917,-2110960732,-1514162242
verifyProof @ crypto.ts:256
Stream.ts:105  coil-extension:background:Stream  error streaming. retry in 2s. err= [privacy pass]: unable to verify dleq proof. Error: [privacy pass]: unable to verify dleq proof.
    at AnonymousTokens._verifyProof (chrome-extension://ghabfhkknmadjoihgnlpgpaihlmeheke/background.js:60690:19)
    at async chrome-extension://ghabfhkknmadjoihgnlpgpaihlmeheke/background.js:60663:13
    at async AnonymousTokens._populateTokensNow (chrome-extension://ghabfhkknmadjoihgnlpgpaihlmeheke/background.js:60666:9)
```
Browser: Chromium

**Comment by sentientwaffle** [comment]
It should be working now. This is due to a commitment rotation issue on the cbs. I'm working on a fix, but have restarted the cbs so that it works in the mean time. Thanks!
